### PR TITLE
feat: better tables

### PR DESCRIPTION
**Pull request by anttio**
## 🖼 Context
Tables by default don't have any styles in Neptune. You have to add `.table` CSS to tables to get basic styling. When using Markdown you needed to add `{.table}` to each table that you wanted to style. This PR removes the manual need to add these classes and does it with a Markdown plugin. By default all tables inside Markdown content will be using `.table-bordered` class. This PR adds the possibility to create tables without table headers and the possibility to create multiline tables.

### Before
image

### After
image

### CODE REVIEW

**Review by gusso — APPROVED** [review]
Yes this is clearly a massive improvement, happy to merge to start. I just feel like I might be missing the vertical separator in columns, but I understand it might be not be very useful because the text might create the separation on our brain already. Did you try it already?

**Comment by gusso** [comment]
Is it a technical constraint that we didn't add branch previews on this repo yet, or you just didn't get to it yet?

**Comment by anttio** [comment]
> Yes this is clearly a massive improvement, happy to merge to start. I just feel like I might be missing the vertical separator in columns, but I understand it might be not be very useful because the text might create the separation on our brain already. Did you try it already?

I thought about the line between columns but opted not adding it because we don't have it in Neptune CSS. I'd try to use those styles as much as possible.

**Comment by anttio** [comment]
> Is it a technical constraint that we didn't add branch previews on this repo yet, or you just didn't get to it yet?

This is on the todo list. I don't have enough rights in this repo so I could set it up.

**Pull request merged**
